src/include/zf_internal/timestamping.h, src/tests/zf_unit/efrxtimestamping.c
Fix regression found building unit test suite due to ef_vi's new sub-nanosecond resolution timestamping API (Xilinx-CNS/onload@9bd12fde14).
```
cc build/gnu_x86_64-zf-devel/obj/tests/zf_unit//efrxtimestamping.o build/gnu_x86_64-zf-devel/obj/tests/zf_unit//../tap/tap.o build/gnu_x86_64-zf-devel/lib/libonload_zf_static.a -lm -lpthread -lrt -lstdc++ -o build/gnu_x86_64-zf-devel/bin/zf_unit/efrxtimestamping
/usr/bin/ld: build/gnu_x86_64-zf-devel/obj/tests/zf_unit//efrxtimestamping.o: in function `get_timestamp_qns(int, unsigned int, unsigned int, unsigned int)':
/home/okt-yuri/work/tcpdirect/src/tests/zf_unit//efrxtimestamping.c:99: undefined reference to `ef10_receive_get_timestamp_with_sync_flags_internal'
/usr/bin/ld: build/gnu_x86_64-zf-devel/obj/tests/zf_unit//efrxtimestamping.o: in …
```
=> ON-15682: update for ef_vi sub-nanosecond timestamp API

.github/workflows/perform_build.yml, Makefile, ci/test.groovy, src/include/zf_internal/utils.h, src/tests/zf_unit/Makefile.inc, src/tests/zf_unit/netns.sh
This commit makes a few minor changes to the tests:
- allow the Jenkins tests to fail and continue with the rest of the pipeline;
- run through all tests in GitHub actions, delaying failure to the end;
- log failed tests to the perform_build GitHub action stage summary;
- move the `testmisc` target to Jenkins for now, until it is fixed;
- flush stdout in assertions to avoid `SIGABRT` losing test output;
- switch to using the public onload repository for GitHub actions;
- improve skipping packetdrill tests for GitHub actions; and
- remove unused valgrind test wrappers.
- GitHub actions run [with a failure](https://github.com/jfeather-amd/tcpdirect/actions/runs/8802425878) (before moving testmisc to Jenkins), scroll down on the linked page for the failure summary
- Passing GitHub action …
=> cleanup: CI tweaks

.github/workflows/perform_build.yml
Problem: 
https://github.com/Xilinx-CNS/tcpdirect/actions/runs/8814928979/job/24195841663
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
=> cleanup: use apt-get rather than apt in github actions

src/include/zf_internal/private/zf_emu.h
The __DECLARE_FLEX_ARRAY macro which we now use in onload, results in a build failure for zf_emu as gcc will complain that a flex array is not the last element in a struct. Additionally, since zf_emu is technically C++ and not C an empty struct has a non-zero size. This commit addresses both of these issues by redefining the __DECLARE_FLEX_ARRAY macro in zf_emu so that the flex array is now just zero-length and removes the empty struct declaration.
Ran `make test` and unit tests passed
Also ran `zfsink`/`zfsend` as a sanity test which ran fine.
=> ON-15817: Fix flex array declaration macro in zf_emu

src/lib/zf/private/zf_emu_superbuf.h
On older distros __DECLARE_FLEX_ARRAY macro is not defined and so builds fail. Fix this by including the definition from zf_emu.h into zf_emu_superbuf.h
Jenkins pipeline passes (don't know if I can post links here or not), but some tests are a bit flaky.
Also ran unit tests on my DUT with `make test`. There were some failures, but the same tests failed with old versions of onload+zf without my recent fixes, so I don't think it is a regression (potentially just a setup issue).
New versions:
zf: 2b2303850e664594db4a03a89cd6ecd8b61c2018
onload: Xilinx-CNS/onload_internal@8e9a3295b45432efb9b7773a2e6a2e14074bc136
"Old" versions:
zf: 38fc592dc1bd76be474a373003a44e60ab29624e
onload: Xilinx-CNS/onload_internal@75fa622f516a60d9600bf14956125b6c8956730d
Failing tests:
* `zfstackdump`
* …
=> ON-15817: Cleanup: Fix missing macro definition

src/include/zf_internal/tx_reports.h, src/tests/zf_unit/zftimestamping.c
Fixes problem whereby TCPDirect treated the bottom two bits of the timestamp nanosecond part as sync flags when these have now moved to a separate field in the event structure.
=> ON-15689: use public accessor macros to read ef_vi tx ts data

src/lib/zf/private/reactor.c
This change updates tcpdirect to use the new timestamping API introduced in Xilinx-CNS/onload@8214875f34c5c3589afd0644d2db00b5f472aceb, and also fixes build issues due to the deprecation of old functions.
=> ON-15255: use new unified ef_vi timestamping API

src/include/zf_internal/tx_warm.h, src/lib/zf/tx_warm.c
Change has been made to deprecate the architecture specific and transmit method specific warming functions. Generic functions for enabling or disabling transmit warming functionality should be used instead.
This commit updates TCPDirect to use the generic ef_vi functions.
Testing was done with zftcppingpong_sleep
Below is perf trace showing new generic methods used on X3 for transmit warming.
Test was also ran on X2.
=> ON-15163: Update to use generic warming functions

src/lib/zf/private/reactor.c, src/lib/zf/private/zf_emu.c
Commit da134ec0d456 (ON-15255: use new unified ef_vi timestamping API, 2024-07-01) was an improper patch, and used to wrong packet reference; instead of referencing the ef_vi rxpkt it instead tried to reference the TCPDirect packet store. This change references the correct packet to correctly extract a timestamp.
This change also teaches zf_emu to expect sub-nanosecond resolution timestamps, rather than the previous clobbering of the lower-order bits in the nanoseconds field.
zf_emu is happy running x3 tests again, although why they were always happy on github is a mystery to me.
=> ON-15255: use ef_vi packet in timestamp calls

ci/test.groovy, scripts/zf_mkdist
This option is passed through to zf_make_tarball and is used as the start of the generated tarball name. Previously, zf_mkdist would specify this as "zf", but this was dropped in Commit 05f83369e204 ("ON-15875: use onload tarball in Jenkins pipeline") which meant the new default was "tcpdirect" to match the existing Jenkins pipeline. However, this broke other consumers of zf_mkdist that expected a tarball starting with "zf" to be generated. As such, this change both adds the option for this to be configured, to be used in the Jenkins pipeline, and reverts to the previous default name prefix "zf".
Manually generated a tarball as below to verify new behaviour:
```
$ ./scripts/zf_mkdist ../onload.tgz
[ ... ]
Written zf-bb4df1d6ebc60ee0cad1372823cce0426f7f1321.tgz
$ ./scripts/zf_mkdist --name …
```
=> ON-15875: add --name option to zf_mkdist

README.MD, ci/test.groovy, scripts/tcpdirect_misc/tcpdirect.spec, scripts/zf_make_official_srpm, scripts/zf_mkdist
Put TCPDirect source files instead of pre-built binaries into the SRPM package generated by the `zf_make_official_srpm` script.
It is quite a crude PR because, for instance, it does not list the tarball files explicitly and can catch temporary text editor files into the tarball, but there are more series to come to address it.
TODO:
=> ON-15664: Generate SRPM with sources and not pre-built binaries

scripts/tcpdirect_misc/tcpdirect.spec
Packaging Guidelines: The BuildRoot: tag ... SHOULD NOT be used.
https://docs.fedoraproject.org/en-US/packaging-guidelines/
=> cleanup: Remove BuildRoot tag in SPEC file

Makefile, Makefile.onload, src/lib/zf/Makefile.inc, src/lib/zf/shim/Makefile.inc, src/lib/zf/zf.c, src/tests/zf_internal/Makefile.inc, src/tests/zf_unit/Makefile.inc, src/tools/zf/Makefile.inc
~~Built ontop of PR #22, but with those changes rebased onto the newest version of master. When #22 is rebased/merged I'll remove these extra commits, for now just focus on the 2 most recent commits.~~
Not technically needed, but now something like `ONLOAD_TREE=../onload make` should work.
If ONLOAD_TREE is set then the build will proceed as before, otherwise
now it will try to build against system installed libraries/headers.
Building with ZF_DEVEL=1 will still require setting ONLOAD_TREE due
since it includes some files from within onload's src tree.
Installed `onload` and `onload-devel` rpms, then built tcpdirect with `make`.
=> ON-15945: Build tcpdirect against system installed onload

README.MD, scripts/tcpdirect_misc/tcpdirect.spec, scripts/zf_mkdist
Previously, in order to build the tcpdirect binary rpm you would have to define the `onload_tarball` macro so that the build system would have all the requisite libraries and headers. Now that we have the `onload-devel` package (and have included citools.a in `onload`), we can use the system installed onload when building tcpdirect and do away with the macro.
The functionality of `onload_tarball` is still preserved in case a user wants to build from a specific version of onload but doesn't want to install it on their system. Additionally, if you want to build the socket shim using `zf_mkdist` you must specify the onload tarball to use as the shim requies `ZF_DEVEL=1` which in turn requires a full copy of the onload source code.
If `onload` and `onload-devel` packages were installed on the …
=> ON-15945: Add option to build RPM from system installed onload

scripts/zf_mkdist
Had to disable a warning where `${copy_to_tmpdir}` wasn't double-quoted, but I've left a comment explaining why
Shellcheck no longer complains
=> Cleanup: Fix shellcheck warning in zf_mkdist

.github/workflows/perform_build.yml, versions.yaml
Now that Xilinx-CNS/onload@v8_1 exists alongside the branch Xilinx-CNS/tcpdirect@v8_1, we want to use that for builds and testing instead. This change also renames the release tag mechanism with an alternative version string as that makes more sense.
GHA [now fails](https://github.com/jfeather-amd/tcpdirect/actions/runs/10470331764/job/28995268477) (as expected), fixed by #35.
=> ON-15724: replace release tag with alternative version

src/include/zf_internal/private/zf_stack_def.h, src/include/zf_internal/zf_stackdump.h, src/lib/zf/doxygen/040_using.dox, src/lib/zf/private/stack_alloc.c, src/lib/zf/udp_tx.c, src/lib/zf/zf_stackdump.c, src/tools/zf/zf_stackdump.c
Added to view attributes in the output of the `zf_stackdump dump`
```
dellr250u:~/devel/fgit/test-onload-git/tcpdirect/build/gnu_x86_64/bin$ ./zf_stackdump dump
============================================================
onload version=27eb4307c8 2023-11-15 onload-8.1.2
tcpdirect version=8.1.3 onload-8.1 tcpdirect-8.1 0c08e35 2024-05-03 v8_1
name=ens1f0/10a interface=ens1f0 vlan_id=65535
pool: pkt_bufs_n=21632 free=17537
config: tcp_timewait_ticks=666 tcp_finwait_ticks=666 ctpio_threshold=64
config: tcp_initial_cwnd=0 ms_per_tcp_tick=90
alts: n_alts=0
stats: ring_refill_nomem=0 cplane_alien_ifindex=0
tcp_retransmits=0
discards: discard_csum_bad=0 discard_mcast_mismatch=0
discard_crc_bad=0 discard_trunc=0 discard_rights=0
discard_ev_error=0 discard_other=0 discard_inner_csum_bad=0 …
```
=> ON-15038: View zf attibutes from zf_stackdump

src/include/zf_internal/zf_state.h, src/lib/zf/zf.c
If libefcp.so can't be found then zf_init will fail, but won't report this to the program that called `zf_init`. This meant that any programs that failed for this reason would not know that they failed, as the `rc` returned would be that from the already non-negative `zf_hal_init` call earlier in the function. A side effect of this was that, as the `zf_state.cp.*` function pointers hadn't been initialised, an app would segfault. 
To solve these problems:
1. 7a4fca63878b03f3dadd62a372115ade2d30690f correctly reports failure of `zf_init` in such cases
2. 6f324d6ffddfc375da7003e8cb92f8a738bf21d3 provides default implementations which, to my best effort, will hopefully return the standard "this failed" values
3. 6aabee5fd440f1d812c7ede2650fee74623796f3 fixes an unearthed issue where `dlclose` …
=> ON-16016: more gracefully handle missing libefcp.so

doc/ChangeLog, doc/ReleaseNotes
Note:
- Installation instructions require subsequent updates.
- Changes are too few and of ambiguous categorisation to split into sublists - 'feature' and 'bug fixes' lists merged in recent release changelogs to be less jarring to read as a whole.
=> cleanup: update distfiles

doc/ReleaseNotes
The existing instruction were sufficient for those cases, and the only new one is DEB packaging AFAIK.
=> ON-16081: update installation instructions in release notes

scripts/tcpdirect_misc/tcpdirect-extract-notes, scripts/zf_make_tarball
Ran jenkins pipeline. No `ReleaseNotes.txt` in the artifacts, and unzipping one of the `.zip` packages showed that it was not included:
```
$ unzip tcpdirect-8.1.3.5-srpm-doxbox.zip
Archive:  tcpdirect-8.1.3.5-srpm-doxbox.zip
inflating: tcpdirect-8.1.3.5-1.src.rpm
inflating: tcpdirect-8.1.3.5-ChangeLog.txt
inflating: tcpdirect-8.1.3.5-LICENSE.txt
```
=> ON-16084: Don't include ReleaseNotes in packages

scripts/zf_mkdist
Previously zf_mkdist would just rm certain sub-directories from build tree before starting a different build type. This was fine when all builds used an onload tarball. However, now that tcpdirect can be built against a system installed onload this can cause issues as these subdirectories don't necessarily exist. This can be resolved by rm-ing the entire build directory and continuing from that point.
Manual inspection. Previous when calling `zf_mkdist` it would say that it was build ndebug binaries, but then `make` would say `nothing to be done for all` (or similar) and grepping for `-DNDEBUG` in the build logs wouldn't get anything.
Now the `NDEBUG` builds are actually happening
=> Cleanup: Actually build ndebug when building from installed packages

scripts/zf_mkdist
I broke the build system in #44 by deleting the produced artifacts while cleaning the build directory for the next part of the process. This approach expands on the previous one by removing all subdirectories of `build_dir` that aren't equal to `artifact_dir`
Manual testing using both onload tarball and install rpms. Here is the list of files in the new tarball built with the shim:
```
zf-86dc1ffb921bcf33061d723a721b0a4e77332754/
zf-86dc1ffb921bcf33061d723a721b0a4e77332754/debug/
zf-86dc1ffb921bcf33061d723a721b0a4e77332754/debug/bin/
zf-86dc1ffb921bcf33061d723a721b0a4e77332754/debug/bin/zf_stackdump
zf-86dc1ffb921bcf33061d723a721b0a4e77332754/debug/lib/
zf-86dc1ffb921bcf33061d723a721b0a4e77332754/debug/lib/libonload_zf.so.1
zf-86dc1ffb921bcf33061d723a721b0a4e77332754/debug/lib/libonload_zf …
```
=> ON-16089: Remove non-artifact build directories in zf_mkdist

doc/ReleaseNotes
Apologies for the second PR. I've taken @dchadwic-xilinx's suggestion, reworded commit log (no point in issue number that doesn't exist) then reordered the release notes and woven the onload-devel theme through.
=> cleanup: iterate on pr/47 onload-dev clarification

scripts/zf_mkdist
Testing done with change reports entire tmp dir is being cleaned up:
```
$ ./scripts/zf_mkdist --shim --version fbeb769bf0bfda9e7e042779c9272646b6b57213 onload/onload-a42bb29e3e8e.tgz
...
zf-fbeb769bf0bfda9e7e042779c9272646b6b57213/src/tests/trade_sim/trader_tcpdirect_ds_efvi.c
zf-fbeb769bf0bfda9e7e042779c9272646b6b57213/src/tests/trade_sim/trader_tcpdirect_ds_efvi_ct_rx.c
zf-fbeb769bf0bfda9e7e042779c9272646b6b57213/src/tests/trade_sim/utils.c
zf-fbeb769bf0bfda9e7e042779c9272646b6b57213/src/tests/trade_sim/utils.h
Written zf-fbeb769bf0bfda9e7e042779c9272646b6b57213.tgz
Deleting /tmp/tmp.Lk9Zp9UOxR
```
Example succeeding build log from runbench without change shows only artifact dir is being cleaned up:
```
...
21:49:17.816	zf-03cff7ff8f3c/src/tests/trade_sim/trader_tcpdirect_ds_efvi_ct_rx. …
```
=> ON-16094: Ensure complete tmp dir is cleaned up at end of build

src/tests/zf_apps/zfsink.c
Modified zfsink to use a monitoring thread to output traffic rate every second, as with efsink in Onload.
Tested with high packet rate (>5Mpps) and high throughput (>9Gbps) to confirm output is correctly formatted.
Timestamps work as before and are output every packet.
Monitoring thread can be disabled using '-q'.
=> ON-16111: use monitor thread in zfsink to allow testing higher rates

src/lib/zf/zf.c
Closes #55 .
* Built zf using installed onload.
* Moved libefcp* into a new location (`/tmp/`) and removed `libefcp.so` leaving `libefcp.so.1` and `libefcp.so.1.0.0`
* Ran zfsink
Without this patch it fails to load to the library, with the patch it progresses past that point.
=> ON-16211: Use proper SONAME for libefcp

src/tests/zf_unit/zfattrs.c
This fixes a unit test failure where more than the number of expected tests are run. Introduced in commit:
25232a5b0e6ee016d30a24e95bd280cc82af2505
Ran `make testmisc` which runs the zf_attrs unit tests. They pass.
=> ON-15400: Fix unit test breakage

.github/actions/build/action.yml, .github/actions/install-dependencies/action.yml, .github/actions/test/action.yml, .github/workflows/perform_build.yml, ci/test.groovy, src/tests/zf_unit/Makefile.inc, src/tests/zf_unit/netns.sh
The motivation behind this patch series is to allow the TCPDirect GitHub Actions to be run from other repositories, specifically onload. This is useful to make sure onload changes don't break the build/tests of TCPDirect.
The first commit is the main work here, which extracts actions (install dependencies, build, and test) from the build workflow and places them into their own individual action files which can be called independently. The remaning commits work around issues caused by private repos having less powerful runners. The second commit, to add a timeout multiplier, is actually more for myself as my dev machine is too slow to pass some of the superbuf tests - filtering out slow tests is sufficient to pass GHA on slower runners.
- [TCPDirect GHA is effectively a …
=> ON-16235: refactor GHA to be reusable and add unit test options

.github/actions/test/action.yml, src/tests/zf_unit/Makefile.inc
I found that, during merging of the corresponding onload change, the `zfquiesce_waittw` test failed, so have added it to the slow tests. At the same time, I spotted that I had accidentally dropped the `-k` from the `make test` invocation to continue running through tests even if one fails.
- [GHA pass](https://github.com/jfeather-amd/tcpdirect/actions/runs/12670600906/job/35310600272)
- `make testmisc` with `ZF_RUN_SLOW_TESTS=0` skips `zfquiesce_waittw`
=> ON-16235: continue tests on fail in GHA and expand slow test set

src/tests/zf_unit/Makefile.inc
I had this fail in one of my [GHA runs](https://github.com/Xilinx-CNS/onload_internal/actions/runs/12885919438), where this is typically consistent elsewhere.
- Built/ran unit tests manually
- [GHA still happy](https://github.com/jfeather-amd/tcpdirect/actions/runs/12889995090/job/35938542864) (and still running this from tcpdirect)
=> ON-16275: add zfmultizock_bond to slow/unreliable test list

src/lib/zf/private/stack_alloc.c
Since `ctpio_mode` can be <0, using a signed int is more appropriate. (https://github.com/Xilinx-CNS/tcpdirect/blob/tcpdirect-9.0.0/src/lib/zf/private/stack_alloc.c#L52-L54)
We also decided that there is no obvious reason for the no-poison flag to be set in the event that `ctpio_mode < 0`. My assumption is that there was an earlier decision that any future 'no-poisoning' CTPIO modes would also have negative values like `CTPIO_MODE_SF_NP=-1`.
Another solution would be to use an enum but I do not see examples of this being used elsewhere in this codebase. This solution is the least disruptive imo.
As a test, I created a `sf-np` VI and then a `ct` VI (on same interface) and strated tx'mitting with the `ct` VI.
- Base v8_1: saw `rx_bad` accumulate on remote end.
- v8_1 + this patch: no …
=> ON-16265: Set no-poison vi flag when ctpio_mode=sf-np

src/include/zf_internal/tx_send.h, src/include/zf_internal/zf_stack.h, src/lib/zf/private/reactor.c, src/lib/zf/private/stack_alloc.c, src/lib/zf/private/stack_fast.c, src/lib/zf/stack.c, src/lib/zf/tx_warm.c, src/lib/zf/udp_tx.c
This means the correct code paths are taken.
Same as https://github.com/Xilinx-CNS/tcpdirect/pull/75 - traffic passes on zfsink/zfsend
zf_emu tests pass
=> ON-16435: Add arch checks for ef10ct

src/tests/zf_unit/Makefile.inc
Fix the following build-time error when both ZF and Onload are built from git-tree:
```
$ ZF_DEVEL=1 ONLOAD_TREE=... make
...
/usr/bin/ld: cannot find -lciul1
collect2: error: ld returned 1 exit status
```
A problem here was src/tests/zf_unit/Makefile.inc setting `LD_FLAGS` and these being passed to src/tests/trade_sim/Makefile indirectly via the top-level Makefile. It is only a problem when Onload is not installed in the OS.
---
Testing with `onload-9.0`:
1. In-tree Onload with in-tree ZF, i.e. `ONLOAD_TREE=~/lab/onload_internal make` (Pass)
2. The same as (1) with `ZF_DEVEL=1`, i.e. `ZF_DEVEL=1 ONLOAD_TREE=~/lab/onload_internal make` (Pass)
3. Installed Onload with `./scripts/zf_make_official_srpm` and `rpmbuild --rebuild ~/rpmbuild/SRPMS/tcpdirect-8ee7d8ffec6cced9b9ee898871f9f52d35b52ea …
=> ON-16450: Fix ZF_DEVEL=1 builds

CONTRIBUTING.md, DEVELOPING.md, LICENSE, README.md
Make the TCPDirect github look more like the Onload repo.
=> ON-15695: improve developer documentation

src/lib/zf/pool.c, src/lib/zf/stack.c
Allocated 2MB huge pages and 1GB huge pages remains zero. System default set via kernel command line to be 1G.
Before:
```
[server01:tcpdirect]$ ZF_ATTR="interface=eth0" ./build/bin/zf_apps/static/zfsink -r 192.1.2.3:25000
ERROR: main: ZF_TRY(zfur_addr_bind(ur, ai_local->ai_addr, ai_local->ai_addrlen, NULL, 0, 0)) failed
ERROR: at src/tests/zf_apps//zfsink.c:365
ERROR: rc=-28 (No space left on device) errno=28
Aborted (core dumped)
```
After
```
[server01:tcpdirect]$ ZF_ATTR="interface=eth0" ./build/bin/zf_apps/static/zfsink -r 192.1.2.3:25000
0                0                0
^C
```
=> ON-16341: force 2MB huge page allocation to run on 1GB default systems

src/include/zf_internal/attr_tmpl.h, src/lib/zf/private/stack_alloc.c
```
$ LD_LIBRARY_PATH=~/git/onload_internal/build/gnu_x86_64/lib/cplane ZF_ATTR=interface=enp193s0f0\;tph_mode=qwerty ./build/gnu_x86_64/bin/zf_apps/static/zfsink 192.168.100.100:26262
1000 | Bad tph_mode attribute; must be one of: none, enable, steering
ERROR: main: ZF_TRY(zf_stack_alloc(attr, &stack)) failed
ERROR: at src/tests/zf_apps//zfsink.c:265
ERROR: rc=-22 (Invalid argument) errno=0
Aborted (core dumped)
```
```
$ LD_LIBRARY_PATH=~/git/onload_internal/build/gnu_x86_64/lib/cplane ZF_ATTR=interface=enp193s0f0 ./build/gnu_x86_64/bin/zf_apps/static/zfsink 192.168.100.100:26262
```
```
$ LD_LIBRARY_PATH=~/git/onload_internal/build/gnu_x86_64/lib/cplane  ./build/gnu_x86_64/bin/zf_stackdump dump | grep flags
nic0: vi=4 vi_flags=3000000 nic_flags=1 intf=enp193s0f0 index=6 hw=5A0
```
``` …
```
=> ON-16925: add attribute to control TPH
